[package]
name = "llmterm"
version = "0.1.1"
edition = "2021"
author = "Timothy Schmidt <timschmidt@gmail.com>"

[dependencies]
kalosm = {version = "0.3.2", features=["language", "cuda"]}
tokio = "1.42.0"
